package templates

type ScaffoldTemplate struct {
	Name        string
	Description string
	Directories []string
}

var DefaultStructure = []string{
	"src",
	"docs",
	"tests",
	".github",
	".github/workflows",
}

var ScaffoldTemplates = map[string]ScaffoldTemplate{
	"go": {
		Name:        "Go",
		Description: "Standard Go project layout",
		Directories: []string{
			"cmd",
			"internal",
			"pkg",
			"api",
			"configs",
			"scripts",
			"build",
			"deployments",
			"test",
			"docs",
			"tools",
			"third_party",
			".github",
			".github/workflows",
		},
	},
	"python": {
		Name:        "Python",
		Description: "Standard Python project layout",
		Directories: []string{
			"src",
			"tests",
			"docs",
			"scripts",
			".github",
			".github/workflows",
		},
	},
	"node": {
		Name:        "Node.js",
		Description: "Standard Node.js project layout",
		Directories: []string{
			"src",
			"lib",
			"test",
			"tests",
			"docs",
			"scripts",
			".github",
			".github/workflows",
		},
	},
	"rust": {
		Name:        "Rust",
		Description: "Standard Rust project layout",
		Directories: []string{
			"src",
			"crates",
			"benches",
			"tests",
			"docs",
			"scripts",
			".github",
			".github/workflows",
		},
	},
	"minimal": {
		Name:        "Minimal",
		Description: "Bare minimum project structure",
		Directories: []string{
			"src",
			"docs",
			".github",
			".github/workflows",
		},
	},
}

func GetScaffoldTemplate(name string) (*ScaffoldTemplate, bool) {
	tmpl, ok := ScaffoldTemplates[name]
	return &tmpl, ok
}

func ListScaffoldTemplates() []string {
	var names []string
	for name := range ScaffoldTemplates {
		names = append(names, name)
	}
	return names
}

func GetGitignore(template string) string {
	gitignores := map[string]string{
		"go": `# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output of go coverage
*.out

# Dependency directories
vendor/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
`,
		"python": `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.env
.venv
env/
venv/
ENV/

# IDE
.idea/
.vscode/
*.swp
*.swo

# Testing
.coverage
htmlcov/
.pytest_cache/
.tox/

# OS
.DS_Store
Thumbs.db
`,
		"node": `# Dependencies
node_modules/
.pnp
.pnp.js

# Build
build/
dist/

# Testing
coverage/

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# IDE
.idea/
.vscode/
*.swp
*.swo

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# OS
.DS_Store
Thumbs.db
`,
		"rust": `# Generated by Cargo
/target/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
`,
		"minimal": `# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local
`,
	}

	if gitignore, ok := gitignores[template]; ok {
		return gitignore
	}
	return gitignores["minimal"]
}
